import React, { useState } from "react";
import { Api } from "./services/Api";
import type { Letter } from "./types/letter";

const api = new Api();

const App: React.FC = () => {
  const [sender, setSender] = useState<string>("");
  const [receiver, setReceiver] = useState<string>("");
  const [content, setContent] = useState<string>("");
  const [message, setMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setMessage(null);

    try {
      // id is usually generated by backend, so omit it here
      const newLetter: Omit<Letter, "id"> = {
        sender: sender || undefined, // send undefined if empty string
        receiver,
        content,
      };
      await api.createLetter(newLetter);
      setMessage("Letter added successfully!");
      setSender("");
      setReceiver("");
      setContent("");
    } catch (error) {
      setMessage("Failed to add letter.");
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        maxWidth: 400,
        margin: "2rem auto",
        fontFamily: "Arial, sans-serif",
      }}
    >
      <h1>Add a New Letter</h1>
      <form onSubmit={handleSubmit}>
        <div style={{ marginBottom: "1rem" }}>
          <label htmlFor="sender" style={{ display: "block", marginBottom: 4 }}>
            Sender (optional):
          </label>
          <input
            id="sender"
            type="text"
            value={sender}
            onChange={(e) => setSender(e.target.value)}
            style={{ width: "100%", padding: 8, fontSize: 16 }}
            placeholder="Sender's name"
          />
        </div>
        <div style={{ marginBottom: "1rem" }}>
          <label
            htmlFor="receiver"
            style={{ display: "block", marginBottom: 4 }}
          >
            Receiver:
          </label>
          <input
            id="receiver"
            type="text"
            value={receiver}
            onChange={(e) => setReceiver(e.target.value)}
            style={{ width: "100%", padding: 8, fontSize: 16 }}
            required
            placeholder="Receiver's name"
          />
        </div>
        <div style={{ marginBottom: "1rem" }}>
          <label
            htmlFor="content"
            style={{ display: "block", marginBottom: 4 }}
          >
            Content:
          </label>
          <textarea
            id="content"
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={4}
            style={{ width: "100%", padding: 8, fontSize: 16 }}
            required
            placeholder="Write your letter content here"
          />
        </div>
        <button
          type="submit"
          disabled={loading}
          style={{ padding: "0.5rem 1rem", fontSize: 16 }}
        >
          {loading ? "Adding..." : "Add Letter"}
        </button>
      </form>
      {message && <p style={{ marginTop: "1rem" }}>{message}</p>}
    </div>
  );
};

export default App;
